#
# This external dependency pulls mu_feature_config for platforms to consume.
#
{
  "scope": "global",
  "type": "git",
  "name": "FEATURE_CONFIG",
  "var_name": "FEATURE_CONFIG_PATH",
  "source": "https://github.com/kuqin12/mu_feature_config.git",
  "version": "54d79dd425c201000457b4e648448d936706068f",
  "flags": ["set_build_var"]
}